name: Test Merly Mentor Action

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-merly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: testpath

      - name: Merly Mentor Check MP
        uses: merly-ai/mentor-action@main
        with:
          mm-key: '${{ secrets.MM_KEY }}'
          checkout-code: false
          path: testpath